name: lint-and-test
on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  lint-and-test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.10'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Run tests
        run: go test ./...
